// Do not edit. This file is machine generated by the Resource DLL Wizard.

library TextDungeon;

{ITE} {DFMFileType} {characterCreation.dfm}
{ITE} {DFMFileType} {connectForm.dfm}
{ITE} {DFMFileType} {Inventory.dfm}
{ITE} {DFMFileType} {mainForm.dfm}
{ITE} {DFMFileType} {mainMenu.dfm}
{ITE} {DFMFileType} {sideForm.dfm}
{ITE} {RCFileType} {Text Dungeon_DRC.rc}

{$R 'characterCreation.dfm' 'Form3:TForm'}
{$R 'connectForm.dfm' 'ConnectionForm:TForm'}
{$R 'Inventory.dfm' 'Form4:TForm'}
{$R 'mainForm.dfm' 'Form1:TForm'}
{$R 'mainMenu.dfm' 'Form2:TForm'}
{$R 'sideForm.dfm' 'sideMenu:TForm'}
{$R 'Text Dungeon_DRC.res' 'Text Dungeon_DRC.rc'}

{$E ENU}

begin
end.
